import { Card, Typography } from 'antd'
import Head from 'next/head';
import React, { FC } from 'react'

interface LoginProps {

}

const Login: FC<LoginProps> = ({ }) => {
  return (
    <>
     <Head>
        <title>Log In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Card>
      <Typography.Title>Login</Typography.Title>
    </Card>
    </>
  )
}

export default Login;