import LoginContainer from "@/components/screens/auth/login";
import React, { FC } from "react";
import Head from "next/head";

interface LoginProps {}

const Login: FC<LoginProps> = ({}) => {
  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <LoginContainer />
    </>
  );
};

export default Login;
