import SignupContainer from "@/components/screens/auth/signUp";
import React, { FC } from "react";
import Head from "next/head";

interface signupProps {}

const Signup: FC<signupProps> = ({}) => {
  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <SignupContainer />
    </>
  );
};

export default Signup;
