import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import LayoutContainer from '@/components/layout'
import { Col, Row } from 'antd'
import { ShareChart } from './components/ShareChart'
import { ShareList } from './components/ShareList'


export default function ChartPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutContainer>
        <Row gutter={8} style={{padding:10}}>
          <Col span={16}>
            <ShareChart/>
          </Col>
          <Col span={8}>
            <ShareList/>
          </Col>
        </Row>
      </LayoutContainer>
    </>
  )
}
