import { Suspense, lazy } from "react";
import Head from "next/head";
// import LayoutContainer from "@/components/layout";
import { HomeContainer } from "@/components/screens";

const LayoutContainer = lazy(() => import("@/components/layout"));

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={<p>Loading......</p>}>
        <LayoutContainer>
          <HomeContainer />
        </LayoutContainer>
      </Suspense>
    </>
  );
}
