import LayoutContainer from '@/components/layout';
import { TradingContainer } from '@/components/screens';
import Head from 'next/head';
import React, { FC } from 'react'

interface indexProps {
  
}

const index: FC<indexProps> = ({  }) => {
  return (
    <>
     <Head>
        <title>Trading</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <LayoutContainer>
      <TradingContainer/>
    </LayoutContainer>
    </>
  )
}

export default index;