import LayoutContainer from "@/components/layout";
import PortfolioCreatorContainer from "@/components/screens/portfolioCreator/component/CreatePortfolio";
import Head from "next/head";
import React, { FC } from "react";

interface indexProps {}

const index: FC<indexProps> = ({}) => {
  return (
    <>
      <Head>
        <title>Portfolio Creator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <LayoutContainer>
        <PortfolioCreatorContainer />
      </LayoutContainer>
    </>
  );
};

export default index;
